services:
  runtime:
    image: ghcr.io/sitepilot/runtime:build
    profiles:
      - donotstart
    environment:
      RUNTIME_VERBOSITY: 2
    build:
      context: ./src
      target: runtime

  php:
    image: ghcr.io/sitepilot/php:build
    profiles:
      - donotstart
    environment:
      RUNTIME_VERBOSITY: 2
    build:
      context: ./src
      target: php

  php-fpm:
    image: ghcr.io/sitepilot/php-fpm:build
    profiles:
      - donotstart
    environment:
      RUNTIME_VERBOSITY: 2
    build:
      context: ./src
      target: php-fpm

  php-nginx:
    image: ghcr.io/sitepilot/php-nginx:build
    profiles:
      - donotstart
    ports:
      - :80
      - :443
    environment:
      RUNTIME_VERBOSITY: 2
    build:
      context: ./src
      target: php-nginx

  php-ols:
    image: ghcr.io/sitepilot/php-ols:build
    profiles:
      - donotstart
    ports:
      - :80
      - :443
    environment:
      RUNTIME_VERBOSITY: 2
    build:
      context: ./src
      target: php-ols

  php-sshd:
    image: ghcr.io/sitepilot/php-sshd:build
    profiles:
      - donotstart
    ports:
      - 2222:2222
    environment:
      RUNTIME_VERBOSITY: 2
      RUNTIME_USER: captain
      RUNTIME_PASSWORD: secret
    build:
      context: ./src
      target: php-sshd

  sidecar:
    image: ghcr.io/sitepilot/sidecar:build
    profiles:
      - donotstart
    build:
      context: ./src
      target: sidecar
