services:
  runtime:
    image: ghcr.io/sitepilot/runtime:build
    profiles:
      - donotstart
    ports:
      - "2222:2222"
    environment:
      RUNTIME_VERBOSITY: 2
      RUNTIME_SSHD_ENABLED: true
      RUNTIME_CRON_ENABLED: true
      RUNTIME_USER: captain
      # Generate with: openssl passwd -1
      RUNTIME_PASSWORD_FILE: /files/password # secret
      RUNTIME_SSHD_AUTH_KEYS_FILE: /files/authorized_keys
    volumes:
      - ./files:/files
    build:
      context: ./src
      target: runtime

  php-cli:
    image: ghcr.io/sitepilot/php:8.3
    profiles:
      - donotstart
    build:
      context: ./src
      target: php-cli

  php-fpm:
    image: ghcr.io/sitepilot/php:8.3-fpm
    profiles:
      - donotstart
    build:
      context: ./src
      target: php-fpm

  php-nginx:
    image: ghcr.io/sitepilot/php:8.3-fpm-nginx
    profiles:
      - donotstart
    ports:
      - "2080:80"
      - "2443:443"
    environment:
      RUNTIME_VERBOSITY: 2
    build:
      context: ./src
      target: php-nginx

  php-ols:
    image: ghcr.io/sitepilot/php:8.3-fpm-ols
    profiles:
      - donotstart
    ports:
      - "2080:80"
      - "2443:443"
    environment:
      RUNTIME_VERBOSITY: 2
    build:
      context: ./src
      target: php-ols
