#!/usr/bin/env bash

set -e
set -u

function to_bool()
{
  if [[ $1 == 'true' || $1 == true || $1 == 1 || $1 == 'Y' || $1 == 'y' ]]; then
    true
  else
    false
  fi
}

function debug()
{
  if [ "$RUNTIME_VERBOSITY" -ge 2 ]; then
    echo "❇️ $1" > /dev/stdout
  fi
}

function info()
{
  if [ "$RUNTIME_VERBOSITY" -ge 1 ]; then
    echo "ℹ️ $1" > /dev/stdout
  fi
}

function warning()
{
  if [ "$RUNTIME_VERBOSITY" -ge 1 ]; then
    echo "⚠️ $1" > /dev/stderr
  fi
}

function error()
{
    echo "🆘 $1" > /dev/stderr
}

function throw()
{
  EXIT_CODE=${2:-1}
  echo "🆘 $1" > /dev/stderr
  exit "$EXIT_CODE"
}

function template()
{
  debug "Generating $1 to $2"
  /runtime/bin/dockerize -template "/runtime/templates/$1":"$2"
}

function file_env() {
	local var="$1"
	local fileVar="${var}_FILE"
	local def="${2:-}"

	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
		throw "Both $var and $fileVar are set (but are exclusive)"
	fi

	local val="$def"
	if [ "${!var:-}" ]; then
		val="${!var}"
	elif [ "${!fileVar:-}" ]; then
		val="$(< "${!fileVar}")"
	fi

	export "$var"="$val"
	unset "$fileVar"
}

function generate_certs()
{
  if [ ! -f "$RUNTIME_CERTS_DIR"/ssl.key ]; then
    mkdir -p "$RUNTIME_CERTS_DIR"
    debug "Generating self-signed SSL certificate to $RUNTIME_CERTS_DIR"
    openssl req -x509 -subj "/C=NL/ST=Gelderland/L=Doetinchem/O=Sitepilot/CN=app.test" -nodes -newkey rsa:2048 -keyout "$RUNTIME_CERTS_DIR/ssl.key" -out "$RUNTIME_CERTS_DIR/ssl.crt" -days 365 &> /dev/null
  fi
}

mkdir -p "$RUNTIME_FILES_DIR"

for FILE in /runtime/entrypoint.d/*.sh; do
  # shellcheck disable=SC1090
  source "$FILE"
done

touch "$RUNTIME_BOOTED_FILE"

if [ -n "$( ls -A '/etc/s6-overlay/s6-rc.d/user/contents.d' )" ]; then
  export S6_KEEP_ENV=${S6_KEEP_ENV:-1}
  export S6_VERBOSITY=${S6_VERBOSITY:-$RUNTIME_VERBOSITY}
  export S6_BEHAVIOUR_IF_STAGE2_FAILS=${S6_BEHAVIOUR_IF_STAGE2_FAILS:-2}
  export S6_CMD_WAIT_FOR_SERVICES_MAXTIME=${S6_CMD_WAIT_FOR_SERVICES_MAXTIME:-0}
  exec /init "$@"
elif test $# -gt 0; then
  exec "$@"
fi
