on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build-and-test-php:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/sitepilot/${{ inputs.target }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=pr,prefix=${{ inputs.version }}-
            type=ref,event=branch,prefix=${{ inputs.version }}-
            type=raw,enable={{is_default_branch}},value=${{ inputs.version }}

      - name: Build and publish image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          target: ${{ inputs.target }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64
          cache-from: type=gha,scope=${{ inputs.target }}-${{ inputs.version }}
          cache-to: type=gha,mode=max,scope=${{ inputs.target }}-${{ inputs.version }}
          provenance: false
          build-args: |
            PHP_VERSION=${{ inputs.version }}
