name: php-fpm

on:
  push:
    branches:
      - '1.x'
    paths:
      - 'src/php-fpm/**'
      - '.github/workflows/php-fpm.yml'
  workflow_dispatch:

jobs:
  php-fpm:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
      fail-fast: true
    with:
      target: php-fpm
      version: ${{ matrix.php }}
    secrets: inherit
