name: php-cli

on:
  push:
    branches:
      - '2.x'
    paths:
      - 'src/php-*/**'
      - 'src/runtime/**'
      - 'src/Dockerfile'
      - '.github/workflows/php-cli.yml'
      - '.github/workflows/build-php.yml'
  workflow_dispatch:

jobs:
  php-cli:
    uses: ./.github/workflows/build-php.yml
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
      fail-fast: true
    with:
      target: php-cli
      tag: ${{ matrix.php }}
      version: ${{ matrix.php }}
    secrets: inherit
