name: php-nginx

on:
  push:
    branches:
      - '2.x'
    paths:
      - 'src/php-*/**'
      - 'src/runtime/**'
      - 'src/Dockerfile'
      - '.github/workflows/php-nginx.yml'
      - '.github/workflows/build-php.yml'
  schedule:
    - cron: "25 3 * * *"
  workflow_dispatch:

jobs:
  php-nginx:
    uses: ./.github/workflows/build-php.yml
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
      fail-fast: true
    with:
      target: php-nginx
      tag: ${{ matrix.php }}-fpm-nginx
      version: ${{ matrix.php }}
    secrets: inherit
