name: php-dev

on:
  push:
    branches:
      - '1.x'
    paths:
      - 'src/php-dev/**'
      - 'src/Dockerfile'
      - '.github/workflows/php-dev.yml'
  workflow_dispatch:

jobs:
  php-dev:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
      fail-fast: true
    with:
      target: php-dev
      version: ${{ matrix.php }}
    secrets: inherit
