name: php

on:
  push:
    branches:
      - '1.x'
    paths:
      - "./src/php"
  workflow_dispatch:

jobs:
  php:
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
      fail-fast: true
    with:
      target: php
      version: ${{ matrix.php }}
    secrets: inherit
