name: php-ols

on:
  push:
    branches:
      - '1.x'
    paths:
      - 'src/sidecar/**'
      - 'src/Dockerfile'
      - '.github/workflows/sidecar.yml'
  workflow_dispatch:

jobs:
  sidecar:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: true
    with:
      target: sidecar
    secrets: inherit
